services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: akshay0ka/rbac:backend
    env_file:
      - ./backend/.env
    ports:
      - "3001:3001"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:3001/api
    image: akshay0ka/rbac:frontend
    env_file:
      - ./frontend/.env.local
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
